name: jupyter-xchem
channels:
  - plotly
  - conda-forge
dependencies:
  - python=3.8
  - pip=20.0.2
  - numpy
  - pandas=1.0.3
  - jupyter
  - plotly=4.6.0
  - plotly-orca
  - scipy=1.4.1
  - psutil
  - requests
  - rdkit=2020.09.1
  - openbabel=3.1.1
  - nglview
  - odfpy
  - xlrd
  - pip:
    - git+https://github.com/oddt/oddt.git@master
